### ISSUE TITLE
Setup Windows binary script page contains an invalid link.

### ISSUE THREAD

**Issue by hiroyukimori** [MicrosoftDocs/cognitive-toolkit-docs#149]
[This page](https://github.com/MicrosoftDocs/cognitive-toolkit-docs/blob/live/articles/Setup-Windows-Binary-Script.md) contains the wrong link.

Incorrect link is the following URL set in "Blog" of "If you want to use Python Tools, CNTK, and Visual Studio Code, see this blog."

The wrong address is below url.
http://dacrook.com/cntk-vs-code-awesome/

I think that a malicious site is set up in this link destination, is it the correct link?

**Comment by thiagocrepaldi** [comment]
It was working some time ago. You can find a cached version here: http://webcache.googleusercontent.com/search?q=cache:xtZcLiXzJ34J:dacrook.com/cntk-vs-code-awesome/+&cd=1&hl=en&ct=clnk&gl=us

I will monitor it for some time and remove it if it doesn't return online soon

**Comment by thiagocrepaldi** [comment]
This has been fixed. I've talked to the author, which provided another URL for the blog entry. Enjoy it
